=== epicsdeb/channelarchiver/ExampleSetup/ArchiveDaemon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD for the ArchiveDaemon Configuration -->
<!ELEMENT daemon (port, mailbox?, engine*)>

<!ELEMENT port   (#PCDATA)>  <!-- TCP port number    -->

<!ELEMENT engine
          (desc, port, config, restart?, dataserver?)>
<!ATTLIST engine directory CDATA #REQUIRED>

<!ELEMENT desc   (#PCDATA)> <!-- Text               -->
<!ELEMENT config (#PCDATA)> <!-- path               -->

<!ELEMENT restart (period,action?)>

<!ELEMENT period (#PCDATA)>
<!ATTLIST period
          type (weekly|daily|hourly|timed) #REQUIRED>
<!-- weekly  Mo|Tu|...|Su HH:MM
     daily   HH:MM
     hourly  (double) hours
     timed   HH:MM/HH:MM  
             (start/duration)
  -->

<!ELEMENT action (#PCDATA)>

<!ELEMENT dataserver (host?)>
<!ELEMENT host (#PCDATA)>

=== epicsdeb/channelarchiver/ExampleSetup/ArchiveDaemon.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE daemon SYSTEM "ArchiveDaemon.dtd">
<daemon>
    <port>4900</port>
    <engine directory='llrf'>
        <desc>LLRF</desc>
        <port>4901</port>
        <config>llrf-group.xml</config>
        <restart>
            <period type='weekly'>We 10:20</period>
            <action>echo Updated index</action>
        </restart>
        <dataserver><host>web2</host></dataserver>
    </engine>
    <!-- Typically, more entries follow:
    <engine directory='hprf'>
        ...
    </engine>
     -->
</daemon>
